import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import css from "../styles/home.module.css"
import Hero from "../components/Hero"
import About from "../components/About"
import Arrangements from "../components/Arrangements"
import { client } from "../lib/client";
import Script from "next/script";
import ToTopBtn from "../components/ToTopBtn"

export default function Home({flowers}) {

  return (
    <Layout>
        <Script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA0U-KJ66LaiOT0Sa5-FzGz3so8Wn7T_N8&libraries=places" />
      <div >
        <Head>
          <title>Apathetic Arrangements</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Body */}
        <main>
          <Hero/>
          <About/>
          <Arrangements flowers = {flowers}/>
          <ToTopBtn/>
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "flower"]';
  const flowers = await client.fetch(query);
  return {
    props: {
      flowers
    }
  }
}