import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import css from "../styles/home.module.css"
import Hero from "../components/Hero"
export default function Home() {
  return (
    <Layout>
      <div >
        <Head>
          <title>Apathetic Arrangements</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Body */}
        <main>
          <Hero/>
          {/* About Us */}
          {/* Menu */}
        </main>
      </div>
    </Layout>
  );
}
